export const NODE_ENV = process.env.NODE_ENV;
export const CLIENT_URL = process.env.CLIENT_URL;
export const SERVER_PORT = process.env.SERVER_PORT; // Server 포트 번호
export const MONGO_HOST = process.env.MONGO_HOST; // MongoDB 호스트 주소
export const MONGO_PORT = process.env.MONGO_PORT; // MongoDB 포트 번호
export const MONGO_DATABASE = process.env.MONGO_DATABASE; // MongoDB DB 이름
export const MONGO_USERNAME = process.env.MONGO_USERNAME; // MongoDB 사용자 이름
export const MONGO_PASSWORD = process.env.MONGO_PASSWORD; // MongoDB 암호
export const BLOCK_CYPHER_COIN = process.env.BLOCK_CYPHER_COIN;
export const BLOCK_CYPHER_CHAIN = process.env.BLOCK_CYPHER_CHAIN;
export const BLOCK_CYPHER_TOKEN = process.env.BLOCK_CYPHER_TOKEN;
